# Generated by Django 3.0.8 on 2020-07-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=200)),
                ('empresa', models.ManyToManyField(to='Djenda_App.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telemovel', models.CharField(max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Djenda_App.Departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Djenda_App.Empresa')),
            ],
            options={
                'ordering': ['empresa', 'departamento'],
            },
        ),
    ]
